// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
 const sidebars = {
  // Sidebar principal con categorías personalizadas
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Chrome DevTools',
      items: [
        'chrome-devtools/overview',
        {
          type: 'category',
          label: 'Paneles',
          items: [
            'chrome-devtools/panels/device-mode',
            'chrome-devtools/panels/elements',
            'chrome-devtools/panels/console',
            'chrome-devtools/panels/sources',
            'chrome-devtools/panels/network',
            'chrome-devtools/panels/recorder',
            'chrome-devtools/panels/performance',
            'chrome-devtools/panels/memory',
            'chrome-devtools/panels/application',
            'chrome-devtools/panels/security',
          ],
        },
        'chrome-devtools/shortcuts',
        'chrome-devtools/troubleshooting',
      ],
    },
    // Puedes mantener la generación automática para otras secciones
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;